### ISSUE TITLE
Notifications Page for consolidated view of activity relating to me  

### ISSUE THREAD

**Issue by mattyg** [GeekGene/MewsFeed#109]
Add a notifications drop-down panel or notifications page linked from the navbar.

This should display a list of recent data changes that relate directly to my agent:
- Mews that mention my profile
- Responses to my Mews
- Licks of my Mews
- Responses to Mews I have also responded to (i.e. activity on yarns I am participating in).

I wonder if this feature is what we *really* want, instead of #66.

**Comment by bierlingm** [comment]
So this would effectively combine a personal source chain query with other queries on Yarns and mentions.

I like this as the better thing instead of #66. People would like (and expect) to be notified of activity that's relevant to them.

**Comment by mattyg** [comment]
I was thinking we may want to move this into the epic of tickets needed for public launch. I feel like it's a critical feature for the app to actually be usable.
