### ISSUE TITLE
Full compatibility with WebKit

### ISSUE THREAD

**Issue by mattyg** [GeekGene/MewsFeed#117]
Ensure app works identically on WebKit as Chromium / Firefox

**Overview**
- Regexp look-behind not supported (#114)
- Some quasar styling elements render improperly (search input)
- Mew submit button doesn't seem to work

**Comment by harlantwood** [comment]
One possibility for some of these issues is to do a basic smoke test (even just load the feed page) in playwright, which tests in all major browsers out of the box, and can be configured to fail on js errors— like the regex issue for example.
