### ISSUE TITLE
Collected bugs / quirks identified in internal testing

### ISSUE THREAD

**Issue by mattyg** [GeekGene/MewsFeed#147]
Please put all the bugs / quirks you've found in internal testing here. 

Screenshots are also appreciated if the description isn't obvious.

**Comment by mattyg** [comment]
If a profile has content in the "location" field, but not the "bio" field, it is improperly displayed next to the "Bio" label:

![image](https://github.com/GeekGene/MewsFeed/assets/159270/c1d0a30e-623b-4b14-bf20-23b68f362ed9)

**Comment by mattyg** [comment]
My own interactions with mews I authored should not appear in my notifications:

![image](https://github.com/GeekGene/MewsFeed/assets/159270/76b74736-0894-4e2b-b0ed-3606cdab0d9a)

**Comment by mattyg** [comment]
I quite like having a "back" button on the MewYarn page. Does it make sense to add this to all the other "list view" pages? 
That would be all pages except for MewsFeed, AgentProfile, and DiscoverCreators.

**Comment by mattyg** [comment]
Read notifications not persisting to localstorage in Launcher

**Comment by bierlingm** [comment]
<img width="1648" alt="Screenshot 2023-06-01 at 11 41 40 AM" src="https://github.com/GeekGene/MewsFeed/assets/9335771/2bf38c75-1e05-4ec8-b6b6-af112ada39c8">

Not sure that this is a bug. I think it's actually desirable behavior. Notifications page shows my own response to my own tweet as a notification.

**Comment by bierlingm** [comment]
> I've gotten used to having a "back" button in the web browser, but we don't have it in Launcher.
> 
> We do have our own in-app "back" button on the MewYarn page. Does it make sense to add this to all the other "list view" pages? That would be all pages except for MewsFeed, AgentProfile, and DiscoverCreators.

I'm for adding the back buttons. Twitter has them too. Just makes navigability easier, as you say, and I don't see a drawback.

**Comment by bierlingm** [comment]
There's an interesting kind of "resize flicker" behavior of the first mew window I opened up when writing. It's as though inputting characters slightly changes the size.

**Comment by mattyg** [comment]
notifications page link always displays unread icon badge upon quitting and restarting launcher

**Comment by mattyg** [comment]
> There's an interesting kind of "resize flicker" behavior of the first mew window I opened up when writing. It's as though inputting characters slightly changes the size.

@bierlingm any chance you could take a screencast of this?
