### ISSUE TITLE
Link Constructor Improvements

### ISSUE THREAD

**Issue by bierlingm** [GeekGene/mewsfeed#172]
Usability notes for the link construction experience from me and @artbrock while playing with it on the train
- Looks like we have display inconsistency between how the link is rendered in the mew writing modal and then in the published mew
- It probably shouldn't include adjacent characters before and after (see image)
- It seems to insert spaces before or after when there are connecting characters it doesn't like
- The direction to go for better usability from here is probably a better link constructor interface with two boxes (text and URL) instead of one (URL only)
- We have a decision to make what continuation characters we want to allow in link construction, whether that's cashtags, hashtags, or links, and we probably want to be consistent across them

**Comment by mattyg** [comment]
> Looks like we have display inconsistency between how the link is rendered in the mew writing modal and then in the published mew

Can you clarify? Is this different than the other bullet points noted?

> It probably shouldn't include adjacent characters before and after (see image)

Can you include the screenshot?

> It seems to insert spaces before or after when there are connecting characters it doesn't like

Can you share an example? How do I reproduce this?

> The direction to go for better usability from here is probably a better link constructor interface with two boxes (text and URL) instead of one (URL only)

Idk, I like the simplicity of using the same interface as other tags: just type the special character then the text, and all text succeeding the special character is included in the link. I think we need to get some users and collect broader feedback first, as we've already done 2 rounds of internal UI revisions.

> We have a decision to make what continuation characters we want to allow in link construction, whether that's cashtags, hashtags, or links, and we probably want to be consistent across them. 

I think I see what you mean, so not only spaces should mark the end of the tag?

In general I really don't think we should put much energy into perfecting the mew input field. It is a huge source of code complexity. In the long term it should be replaced with an customized off-the-shelf wysiwyg editor field (see #120).

**Comment by mattyg** [comment]
Talked with art and got a some more clarity on this issue:

### Link Builder

- Different text is parsed as a link in the input field versus the rendered mew

Example: 
- type `(^link)` in input field
- In input field: open + close paren are included in link
- In rendered mew:
  - inserts space before the caret
  - closed paren included in link
  
- In a hashtag, a trailing paren is *not* included in the link -- the only character allowed is `_`

**Changes to make**
- Special characters included as part of a link should match hashtags
- A space should not be inserted before a link
