### ISSUE TITLE
Limiting Mew Text Length

### ISSUE THREAD

**Issue by jost-s** [GeekGene/MewsFeed#48]
Currently, mew text is limited to 200 characters in validation rules. Let's add that limit to the UI CreateMewField.

**Comment by bierlingm** [comment]
This can be changed fairly simply later on, right? We'll probably want to have longer form text at some point. cc @artbrock

**Comment by mattyg** [comment]
> This can be changed fairly simply later on, right? We'll probably want to have longer form text at some point. cc @artbrock

No it is hard-coded in validation rules. Changing would require forking the DHT.

**Comment by bierlingm** [comment]
OK, I'd like this to allow for future change in some way. Since we care about meaningful conversation, and since 200 characters make that quite difficult, I suggest we afford for this to be something like 4000 characters in the future, but limit it to 480 for the moment.

I guess one pragmatic way to do that would be to later add a new mew type that has a longer length, and then put some condition on the ability to use the new mew type, like for example having bought a nom name.

Do you see another good way to avoid the multiple mew types yet allow us to switch up the allowed mew character length without breaking the DNA later?

**Comment by mattyg** [comment]
> OK, I'd like this to allow for future change in some way. Since we care about meaningful conversation, and since 200 characters make that quite difficult, I suggest we afford for this to be something like 4000 characters in the future, but limit it to 480 for the moment.
> 
> I guess one pragmatic way to do that would be to later add a new mew type that has a longer length, and then put some condition on the ability to use the new mew type, like for example having bought a nom name.
> 
> Do you see another good way to avoid the multiple mew types yet allow us to switch up the allowed mew character length without breaking the DNA later?


Hmm, so I think we have a few options:
- fixed "hard" limit
  - Think of all the cases where we want to allow longer mew length up-front, and hardcode them into the validation rules
- "soft" limit only
  - In validation rules: validate mew length is within some arbitrarily long length (i.e. 4000 characters)
  - in the "official" front-end: limit how many characters users can type into to the create mew text field 
  - in the "official" front-end: truncate displayed mew text to that further limit (or hide mews entirely that are longer than the further limit). 
- progenitor-defined hard limit
  - In validation rules: by default, mew is limited to short length
  - In validation rules: If mew includes the hash of a MewLengthLimitRule action signed by the progenitor, they are allowed to create a mew of whatever length is specified in that MewLengthLimitRule
  - This gives us the flexibility to decide when and how to set those limits down-the-road without forking the DNA, but also makes us the centralized moderators of mew length

We may also want the hard min / max mew length to be a DNA property so other instances of mewsfeed can adjust.

**Comment by bierlingm** [comment]
OK, I've asked Art to weigh in since he mentioned this in our last conversation. I guess we can touch on it later today in the call.

**Comment by mattyg** [comment]
At the meeting today we decided on the following implementation:
- remove the limit from validation rules entirely
- truncate displayed mews to 300 characters with a "see more" button to show the rest
- in the CreateMewField show the character limit, but don't actually prevent the user from typing more characters
