### ISSUE TITLE
[DNA + UI] Refactor state management to let UI poll DNA periodically for changes and implement pagination

### ISSUE THREAD

**Issue by jost-s** [GeekGene/MewsFeed#56]
Currently the UI follows a client-server model where it fetches

1. all mews
2. when accessing a page with a mews feed
and doesn’t manage state in the store.

Todo:
Refactor state management to poll periodically and in pages of 10 mews and maintain global state in the store which mews feeds on different pages access for display.

Details to be specified.

**Comment by mattyg** [comment]
I like this -- maybe we should use holochain-time-index such that when polling you can explicitly fetch mews created within the last X seconds (where X is the time since the last poll). 

Another option would be to use signals, where every time you publish a mew it sends a signal to your followers.

**Comment by jost-s** [comment]
We had decided against the signal option, in case Elon Musk was creating a new mew and sending a signal to his 100 Mio. followers.

**Comment by pegaltier** [comment]
i think 10 by 10 is a little too small, usually 50 by 50 or 100 by 100 works well especially if the amount of data is not too big

**Comment by pegaltier** [comment]
Also it make sense to have endless scroll on the ui but i guess you already thought about that
