### ISSUE TITLE
(Ability to) view all mentions of an Agent on their profile page

### ISSUE THREAD

**Issue by mattyg** [GeekGene/MewsFeed#66]

**Comment by mattyg** [comment]
Reflecting on this further, and remembering our conversation at the last meeting. I wonder if the feature we really want to satisfy the underlying need of this idea is #109.

It seems like Agent's might not want to display all mentions of themselves on their profile page? Perhaps it could be an avenue for spam or abuse? (i.e. if I make 100 mews tagging a profile that includes some derogatory message, then it would be displayed prominently on their profile page).

**Comment by mattyg** [comment]
Actually maybe just linking to the mentions page from the profile page is fine. I'm going to implement that for now.

**Comment by bierlingm** [comment]
> It seems like a user might not want to display all mentions of themselves on their profile page? Perhaps it could be an avenue for spam or abuse? (i.e. if someone makes 100 mews with a derogatory message and tag my profile, then they would be displayed prominently on my profile page).

Yeah, I was thinking along the same lines. But I'm fine with the current solution, especially since changing it later would be mostly a UI issue IIUC.
