### ISSUE TITLE
Set up integration of GitHub with Discord

### ISSUE THREAD

**Issue by bierlingm** [GeekGene/MewsFeed#90]
I asked ChatGPT for how to do this.

> To integrate a Discord channel with a GitHub repository, you can use a webhook. A webhook is a way for an application to send data to another application in real-time. In this case, GitHub can send notifications to Discord whenever certain events happen in a repository, such as when a new pull request is opened or when a commit is made.

> Here are the steps to set up a webhook between GitHub and Discord:

1. In Discord, navigate to the channel you want to receive GitHub notifications in and click on the gear icon to access the server settings.
2. From the server settings, select the "Integrations" tab and click on "Webhooks".
3. Click the "Create Webhook" button and follow the prompts to create a new webhook. You will be asked to give the webhook a name, select the channel it will post to, and customize the webhook's avatar if desired.
4. Once the webhook is created, copy the webhook URL that is generated. You will need to provide this URL to GitHub in order to configure the webhook.
5. In GitHub, navigate to the repository you want to create a webhook for and click on "Settings" in the top navigation bar.
6. From the repository settings, select "Webhooks" from the left-hand menu and click on "Add webhook".
7. Paste the Discord webhook URL you copied earlier into the "Payload URL" field.
8. In the "Content Type" dropdown, select "application/json".
9. Under "Which events would you like to trigger this webhook?", choose the events you want to receive notifications for. For example, if you want to receive notifications when a new pull request is opened, select "Let me select individual events" and then choose "Pull requests" from the list.
10. Click "Add webhook" to save your changes.
11. Now, whenever the events you selected occur in your GitHub repository, a notification will be sent to your Discord channel via the webhook you created. You can customize the webhook settings to control what information is included in the notifications and how they are formatted.

----------------

I get stuck at 5. Can't seem to find the settings for the repository and I suspect it's due to missing permissions for me. @mattyg can you look whether you have them there?

Here's the web hook URL: https://discord.com/api/webhooks/1086614464155103333/2GpqP-M5jHDzR_YYc-fcX23IJS0a0xlA7bVMwTMg__GoPiOOHAoCJ0Z2jkHnumvneKff

**Comment by mattyg** [comment]
@bierlingm Okay I added you as an admin of the github project so you should be able to adjust settings now if needed. I added the discord webhook, and it looks like it's working. Currently it's set to notify the discord api of *everything*, but I'm guessing we'll want to reduce that only a few types of github events. 

You can adjust what events it's sending at Settings > Webhooks > edit and then choosing "Let me select individual events" under "Which events would you like to trigger this webhook?"

**Comment by bierlingm** [comment]
OK, I'll leave it at everything for the moment. If it becomes annoying we can change it.

**Comment by harlantwood** [comment]
> OK, I'll leave it at everything for the moment. If it becomes annoying we can change it.

I like it as is FWIW
