### ISSUE TITLE
Replace node test runner

### ISSUE THREAD

**Issue by mattyg** [GeekGene/MewsFeed#98]
Consider replacing node test runner we're currently using 'tape' with another that offers better output for failing tests.

Some options I like:
- ava: https://github.com/avajs/ava
- vitest: https://vitest.dev

**Comment by harlantwood** [comment]
@mattyg just happened to notice running/passing vitest-based tryorama tests in deepkey: https://github.com/holochain/deepkey/blob/92c76dec30280c8490e0f186f33233886fa96f9b/tests/src/deepkey/deepkey/device-invite-acceptance.test.ts
